### ISSUE TITLE
Trying to update m7lib to 0.6.2 

### ISSUE THREAD

**Issue by buddy9507** [mhancoc7/kodi-addons#3] opened 2019-04-15 07:17 UTC
Keep getting update error the only add on that uses m7lib is animal tv is there a fix?

**Comment by jeremehancock** [comment] 2019-04-15 12:00
The issue is that the TVADDONS repo doesn't have my latest version of m7lib. If you download the m7lib manually and install it then things will work. I have reached out to TVADDONS to have that updated. I will work on setting up my repo to be less dependent on the  TVADDONS repo. Thanks for the heads up

**Comment by jeremehancock** [comment] 2019-04-15 16:59
Ok I have pushed an update to the mhancoc7 repo that should fix this. Unfortunately there was an issue with the repo that will not allow it to automate update. So I recommend that you do a fresh install of the latest version of the mhancoc7 repo. This will fix your issue and has removed the dependency on the TVADDONS resolvers repo. Thank you for reporting. Since I have been able to fully replicate your issue and resolve it I am going to close this issue. Feel free to open a new issue if you still have issues.

**Closed as completed** 2019-04-15 16:59 UTC
